# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    config.ssh.forward_agent = true
    config.ssh.insert_key = false
    config.hostmanager.enabled = true

    config.vm.box = "ubuntu/trusty64"

    config.vm.network :forwarded_port, guest: 8888, host: 8888, auto_correct: true # rgw

    config.vm.hostname = "node1"
    config.vm.network :private_network, ip: "192.168.42.11"

    config.vm.provider 'virtualbox' do |v|
        v.customize ['modifyvm', :id, '--name', 'trusty64-ceph-jewel']
        v.customize ['modifyvm', :id, '--cpus', '4']
        v.customize ['modifyvm', :id, '--memory', 2048]
    end

    config.vm.provision 'shell', path: 'provision.sh'

end